services:
  # 1. Redis Instance
  redis:
    image: redis:7-alpine
    container_name: go_app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass "my_secret_password"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "my_secret_password", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 2. Go Application Placeholder (With Live Reloading)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: squash_it
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/app/data/
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=my_secret_password
      - APP_PORT=:8080
      - DATABASE_NAME=/app/data/squash.db
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
volumes:
  redis_data:
  sqlite_data:
